type Cart {
  id: ID!
  total: Float!
  discountedTotal: Float!
  totalProducts: Int!
  totalQuantity: Int!
  products: [CartItem!]!
  user: User!
}

type CartItem {
  quantity: Int!
  total: Float!
  discountedTotal: Float!
  product: Product!
}

type Product {
  id: ID!
  title: String!
  description: String!
  category: String!
  price: Float!
  rating: Float!
  stock: Int!
  brand: String
  sku: String!
  thumbnail: String!
  reviews: [Review!]!
}

type Query {
  cart(id: ID!): Cart
  carts: [Cart!]!
  product(id: ID!): Product
  products: [Product!]!
  user(id: ID!): User
  users: [User!]!
}

type Review {
  id: ID!
  rating: Int!
  comment: String!
  date: String!
  reviewerName: String!
  reviewerEmail: String!
}

type User {
  id: ID!
  carts: [Cart!]!
  writtenReviews: [Review!]!
  firstName: String!
  lastName: String!
  username: String!
  email: String!
  image: String!
}

