type Product {
  id: ID!
  title: String!
  description: String!
  category: String!
  price: Float!
  rating: Float!
  stock: Int!
  brand: String
  sku: String!
  thumbnail: String!
  reviews: [Review!]!
}

type Query {
  product(id: ID!): Product
  products: [Product!]!
  user(id: ID!): User
  users: [User!]!
}

type Review {
  id: ID!
  rating: Int!
  comment: String!
  date: String!
  reviewerName: String!
  reviewerEmail: String!
}

type User {
  id: ID!
  writtenReviews: [Review!]!
  lastName: String!
  username: String!
  email: String!
  image: String!
}

